"""Backtest the sourcing agent's signal generation against 2 years of historical data.

Replays 1-minute underlying bars from historical_0dte.db, aggregates into 5m candles,
runs the sourcing scoring engine, and compares generated signals against actual
Discord signals that were traded by the buy/sell agent.

Usage:
    python scripts/backtest_sourcing.py                          # last 30 days
    python scripts/backtest_sourcing.py --days 90                # last 90 days
    python scripts/backtest_sourcing.py --start 2025-01-01       # from specific date
    python scripts/backtest_sourcing.py --ticker NVDA            # single ticker
    python scripts/backtest_sourcing.py --compare                # compare vs Discord signals
"""

from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from options_owl.sourcing.data.indicator_engine import compute_indicators
from options_owl.sourcing.filters.penalty_veto import check_penalty_veto
from options_owl.sourcing.filters.quality_gate import check_quality_gate
from options_owl.sourcing.scoring.engine import compute_score
from options_owl.sourcing.scoring.types import Direction, SignalContext, SignalState

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

HIST_DB = os.path.join(os.path.dirname(__file__), "..", "journal", "historical_0dte.db")
SIGNALS_DB = os.path.join(os.path.dirname(__file__), "..", "journal", "owlet-kody", "raw_messages.db")

# Match production sourcing config
SCORE_THRESHOLD = 60
SCAN_INTERVAL_BARS = 3  # scan every 3 5m bars (15 min) to match 3-min scan with data gaps
TICKERS = [
    "SPY", "QQQ", "NVDA", "TSLA", "META", "AAPL", "AMZN",
    "GOOGL", "MSFT", "AMD", "MSTR", "PLTR",
]


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class BacktestSignal:
    """A signal generated by the sourcing engine on historical data."""
    date: str
    time: str
    ticker: str
    direction: str
    score: int
    ema_cross: float
    rsi: float
    macd: float
    volume_ratio: float
    adx: float
    reasons: list[str] = field(default_factory=list)


@dataclass
class DiscordSignal:
    """A Discord signal that was actually traded."""
    date: str
    time: str
    ticker: str
    direction: str
    score: int


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_1m_bars(conn: sqlite3.Connection, ticker: str, date: str) -> list[dict]:
    """Load 1-minute underlying bars for a specific ticker and date."""
    rows = conn.execute(
        """SELECT timestamp, open, high, low, close, volume
           FROM underlying_bars
           WHERE ticker = ? AND date = ?
           ORDER BY timestamp ASC""",
        (ticker, date),
    ).fetchall()

    return [
        {
            "timestamp": r[0],
            "open": r[1],
            "high": r[2],
            "low": r[3],
            "close": r[4],
            "volume": r[5] or 0,
        }
        for r in rows
    ]


def aggregate_to_5m(bars_1m: list[dict]) -> list[dict]:
    """Aggregate 1-minute bars into 5-minute candles."""
    if not bars_1m:
        return []

    candles = []
    bucket: list[dict] = []
    bucket_start = None

    for bar in bars_1m:
        ts = bar["timestamp"]
        # Floor to 5-minute bucket (ms)
        bucket_ts = (ts // (5 * 60 * 1000)) * (5 * 60 * 1000)

        if bucket_start is None:
            bucket_start = bucket_ts

        if bucket_ts != bucket_start:
            # Flush previous bucket
            if bucket:
                candles.append(_flush_bucket(bucket))
            bucket = [bar]
            bucket_start = bucket_ts
        else:
            bucket.append(bar)

    # Flush last bucket
    if bucket:
        candles.append(_flush_bucket(bucket))

    return candles


def _flush_bucket(bars: list[dict]) -> dict:
    """Aggregate a bucket of 1m bars into one 5m candle."""
    return {
        "open": bars[0]["open"],
        "high": max(b["high"] for b in bars),
        "low": min(b["low"] for b in bars),
        "close": bars[-1]["close"],
        "volume": sum(b["volume"] for b in bars),
    }


def load_discord_signals(start_date: str, end_date: str) -> list[DiscordSignal]:
    """Load Discord signals from the signals DB for comparison."""
    if not os.path.exists(SIGNALS_DB):
        return []

    conn = sqlite3.connect(SIGNALS_DB)
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(
            """SELECT ticker, direction, score, created_at
               FROM trade_signals
               WHERE date(created_at) BETWEEN ? AND ?
                 AND score >= 78
               ORDER BY created_at""",
            (start_date, end_date),
        ).fetchall()

        signals = []
        for r in rows:
            created = r["created_at"]
            dt = datetime.fromisoformat(created.replace("Z", "+00:00"))
            signals.append(DiscordSignal(
                date=dt.strftime("%Y-%m-%d"),
                time=dt.strftime("%H:%M"),
                ticker=r["ticker"].upper(),
                direction=r["direction"].upper() if r["direction"] else "",
                score=r["score"],
            ))
        return signals
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Backtest engine
# ---------------------------------------------------------------------------

def run_backtest(
    ticker_filter: str | None,
    start_date: str,
    end_date: str,
    compare: bool,
) -> None:
    """Run the sourcing backtest across historical data."""
    conn = sqlite3.connect(HIST_DB)

    tickers = [ticker_filter.upper()] if ticker_filter else TICKERS
    tickers = [t for t in tickers if t in TICKERS or ticker_filter]

    # Get available trading days
    dates = [
        r[0] for r in conn.execute(
            "SELECT DISTINCT date FROM trading_days WHERE date BETWEEN ? AND ? ORDER BY date",
            (start_date, end_date),
        ).fetchall()
    ]

    print(f"\n{'='*70}")
    print(f"SOURCING BACKTEST: {start_date} → {end_date}")
    print(f"Tickers: {', '.join(tickers)}")
    print(f"Trading days: {len(dates)}")
    print(f"Score threshold: {SCORE_THRESHOLD}")
    print(f"{'='*70}\n")

    all_signals: list[BacktestSignal] = []
    daily_stats: dict[str, dict] = {}
    ticker_stats: dict[str, dict] = defaultdict(lambda: {"signals": 0, "calls": 0, "puts": 0})

    for date_idx, date in enumerate(dates):
        day_signals = 0
        for ticker in tickers:
            bars_1m = load_1m_bars(conn, ticker, date)
            if len(bars_1m) < 50:
                continue

            candles_5m = aggregate_to_5m(bars_1m)
            if len(candles_5m) < 15:
                continue

            # Scan at regular intervals through the day
            for scan_idx in range(SCAN_INTERVAL_BARS, len(candles_5m), SCAN_INTERVAL_BARS):
                window = candles_5m[max(0, scan_idx - 78):scan_idx]
                if len(window) < 10:
                    continue

                # Compute indicators
                indicators = compute_indicators(window)

                # Infer direction
                direction = _infer_direction(indicators)

                # Build scan time from actual bar timestamps
                last_bar_ts_ms = bars_1m[min(scan_idx * 5, len(bars_1m) - 1)]["timestamp"]
                scan_dt = datetime.utcfromtimestamp(last_bar_ts_ms / 1000)
                scan_time_str = scan_dt.strftime("%Y-%m-%dT%H:%M:%S+00:00")

                # Build context and score
                ctx = SignalContext(
                    ticker=ticker,
                    scan_time=scan_time_str,
                    state=SignalState.INDICATED,
                    direction=direction,
                    candles_5m=window,
                    indicators=indicators,
                )

                scored = compute_score(ctx)
                ctx.score_total = scored.score
                ctx.state = SignalState.SCORED

                # Skip rejected by scorer
                if scored.rejected:
                    continue

                # Score threshold
                if scored.score < SCORE_THRESHOLD:
                    continue

                # Quality gate
                if not check_quality_gate(ctx, SCORE_THRESHOLD):
                    continue

                # Penalty veto
                if check_penalty_veto(ctx):
                    continue

                # Collect reasons
                reasons = []
                for tier in [ctx.tier1_direction, ctx.tier2_timing, ctx.tier3_amplifiers,
                             ctx.tier4_risk, ctx.tier5_calibration]:
                    if tier and tier.reasons:
                        reasons.extend(tier.reasons)

                signal = BacktestSignal(
                    date=date,
                    time=scan_dt.strftime("%H:%M"),
                    ticker=ticker,
                    direction=direction.value,
                    score=scored.score,
                    ema_cross=round(indicators.ema_cross_strength, 3),
                    rsi=round(indicators.rsi9, 1),
                    macd=round(indicators.macd_line, 4),
                    volume_ratio=round(indicators.volume_ratio, 2),
                    adx=round(indicators.adx, 1),
                    reasons=reasons,
                )
                all_signals.append(signal)
                day_signals += 1
                ts = ticker_stats[ticker]
                ts["signals"] += 1
                if direction == Direction.CALL:
                    ts["calls"] += 1
                else:
                    ts["puts"] += 1

        daily_stats[date] = {"signals": day_signals}

        # Progress
        if (date_idx + 1) % 20 == 0:
            print(f"  Processed {date_idx + 1}/{len(dates)} days, {len(all_signals)} signals so far...")

    conn.close()

    # --- Results ---
    _print_results(all_signals, daily_stats, ticker_stats, dates)

    if compare:
        discord_signals = load_discord_signals(start_date, end_date)
        _print_comparison(all_signals, discord_signals)


def _infer_direction(indicators) -> Direction:
    """Infer CALL/PUT from indicators (same logic as scanner.py)."""
    bullish = bearish = 0
    if indicators.ema_cross_strength > 0.05:
        bullish += 2
    elif indicators.ema_cross_strength < -0.05:
        bearish += 2
    if indicators.macd_line > 0:
        bullish += 1
    elif indicators.macd_line < 0:
        bearish += 1
    if indicators.vwap > 0 and indicators.last_close > indicators.vwap:
        bullish += 1
    elif indicators.vwap > 0 and indicators.last_close < indicators.vwap:
        bearish += 1
    return Direction.CALL if bullish >= bearish else Direction.PUT


def _print_results(
    signals: list[BacktestSignal],
    daily_stats: dict,
    ticker_stats: dict,
    dates: list[str],
) -> None:
    """Print backtest summary."""
    print(f"\n{'='*70}")
    print(f"RESULTS: {len(signals)} signals over {len(dates)} days")
    print(f"{'='*70}")

    if not signals:
        print("  No signals generated.")
        return

    # Daily averages
    days_with_signals = sum(1 for d in daily_stats.values() if d["signals"] > 0)
    avg_per_day = len(signals) / len(dates) if dates else 0
    print(f"\n  Avg signals/day: {avg_per_day:.1f}")
    print(f"  Days with signals: {days_with_signals}/{len(dates)} ({days_with_signals/len(dates)*100:.0f}%)")

    # Direction split
    calls = sum(1 for s in signals if s.direction == "CALL")
    puts = len(signals) - calls
    print(f"  CALL: {calls} ({calls/len(signals)*100:.0f}%)  |  PUT: {puts} ({puts/len(signals)*100:.0f}%)")

    # Score distribution
    scores = [s.score for s in signals]
    print(f"\n  Score: min={min(scores)} avg={np.mean(scores):.0f} max={max(scores)}")
    for bucket_min in range(60, 101, 10):
        bucket_max = bucket_min + 9
        count = sum(1 for s in scores if bucket_min <= s <= bucket_max)
        bar = "#" * (count // max(1, len(signals) // 30))
        print(f"    {bucket_min}-{bucket_max}: {count:4d} {bar}")

    # Per-ticker breakdown
    print(f"\n  {'Ticker':8} {'Signals':>8} {'CALL':>6} {'PUT':>6}")
    print(f"  {'-'*32}")
    for ticker in sorted(ticker_stats, key=lambda t: ticker_stats[t]["signals"], reverse=True):
        ts = ticker_stats[ticker]
        print(f"  {ticker:8} {ts['signals']:8} {ts['calls']:6} {ts['puts']:6}")

    # Time-of-day distribution
    print(f"\n  Time distribution:")
    hour_counts: dict[int, int] = defaultdict(int)
    for s in signals:
        hour = int(s.time.split(":")[0])
        hour_counts[hour] += 1
    for hour in sorted(hour_counts):
        count = hour_counts[hour]
        bar = "#" * (count // max(1, len(signals) // 30))
        print(f"    {hour:02d}:00  {count:4d} {bar}")

    # Top 10 most recent signals
    print(f"\n  Last 10 signals:")
    print(f"  {'Date':12} {'Time':6} {'Ticker':8} {'Dir':5} {'Score':>5} {'EMA':>7} {'RSI':>5} {'ADX':>5}")
    for s in signals[-10:]:
        print(
            f"  {s.date:12} {s.time:6} {s.ticker:8} {s.direction:5} "
            f"{s.score:5} {s.ema_cross:7.3f} {s.rsi:5.1f} {s.adx:5.1f}"
        )


def _print_comparison(
    sourcing: list[BacktestSignal],
    discord: list[DiscordSignal],
) -> None:
    """Compare sourcing signals against actual Discord signals."""
    print(f"\n{'='*70}")
    print(f"COMPARISON: Sourcing vs Discord Signals")
    print(f"{'='*70}")

    if not discord:
        print("  No Discord signals found in date range.")
        return

    print(f"\n  Sourcing signals: {len(sourcing)}")
    print(f"  Discord signals:  {len(discord)}")

    # Build lookup for matching (date + ticker + direction within 30 min window)
    matches = 0
    sourcing_only = 0
    discord_only = 0

    # Index sourcing signals by (date, ticker)
    sourcing_by_dt: dict[tuple[str, str], list[BacktestSignal]] = defaultdict(list)
    for s in sourcing:
        sourcing_by_dt[(s.date, s.ticker)].append(s)

    matched_discord = set()
    matched_sourcing = set()

    for di, d in enumerate(discord):
        # Normalize direction for comparison
        d_dir = "CALL" if d.direction in ("CALL", "call", "bullish") else "PUT"

        candidates = sourcing_by_dt.get((d.date, d.ticker), [])
        found = False
        for si, s in enumerate(candidates):
            if s.direction == d_dir and id(s) not in matched_sourcing:
                matches += 1
                matched_discord.add(di)
                matched_sourcing.add(id(s))
                found = True
                break

        if not found:
            discord_only += 1

    sourcing_only = len(sourcing) - len(matched_sourcing)

    print(f"\n  Overlap (both found):    {matches}")
    print(f"  Sourcing only:           {sourcing_only} (new opportunities?)")
    print(f"  Discord only:            {discord_only} (sourcing missed)")

    if discord:
        detection_rate = matches / len(discord) * 100
        print(f"\n  Detection rate: {detection_rate:.1f}% of Discord signals also found by sourcing")

    if sourcing:
        unique_rate = sourcing_only / len(sourcing) * 100
        print(f"  Unique signal rate: {unique_rate:.1f}% of sourcing signals are new (not in Discord)")

    # Per-ticker comparison
    print(f"\n  {'Ticker':8} {'Discord':>8} {'Sourcing':>9} {'Overlap':>8} {'Det%':>6}")
    print(f"  {'-'*45}")

    ticker_discord = defaultdict(int)
    ticker_overlap = defaultdict(int)
    for di, d in enumerate(discord):
        ticker_discord[d.ticker] += 1
        if di in matched_discord:
            ticker_overlap[d.ticker] += 1

    ticker_sourcing = defaultdict(int)
    for s in sourcing:
        ticker_sourcing[s.ticker] += 1

    all_tickers = sorted(set(list(ticker_discord.keys()) + list(ticker_sourcing.keys())))
    for t in all_tickers:
        dc = ticker_discord.get(t, 0)
        sc = ticker_sourcing.get(t, 0)
        ov = ticker_overlap.get(t, 0)
        det = f"{ov/dc*100:.0f}%" if dc > 0 else "N/A"
        print(f"  {t:8} {dc:8} {sc:9} {ov:8} {det:>6}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Backtest sourcing agent signal generation")
    parser.add_argument("--days", type=int, default=30, help="Number of days to backtest (default: 30)")
    parser.add_argument("--start", type=str, help="Start date (YYYY-MM-DD)")
    parser.add_argument("--end", type=str, help="End date (YYYY-MM-DD)")
    parser.add_argument("--ticker", type=str, help="Single ticker to backtest")
    parser.add_argument("--compare", action="store_true", help="Compare against Discord signals")
    parser.add_argument("--threshold", type=int, default=60, help="Score threshold")
    args = parser.parse_args()

    score_threshold = args.threshold

    if args.start:
        start_date = args.start
    else:
        start_date = (datetime.now() - timedelta(days=args.days)).strftime("%Y-%m-%d")

    end_date = args.end or datetime.now().strftime("%Y-%m-%d")

    global SCORE_THRESHOLD
    SCORE_THRESHOLD = score_threshold
    run_backtest(args.ticker, start_date, end_date, args.compare)


if __name__ == "__main__":
    main()
